require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/cable.yml'
    - 'config/environment.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/puma.rb'
    - 'config/secrets.yml'
    - 'config/spring.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/templates/**/*'
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6

Rails:
  Enabled: true
