name: Cobudget UI

on:
  push:
    branches:
      - master
    paths:
      - "ui/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      uses: actions/setup-node@v1
      with:
        node-version: '6'
    - run: |
        npm install -g gulp bower
        npm install --quiet
        NODE_ENV=production npm run build
      working-directory: ui
    - name: Deploy to S3
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws s3 cp ./ui/build/ s3://${AWS_S3_BUCKET}/ --recursive
