name: Cobudget UI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      uses: actions/setup-node@v1
      with:
        node-version: '6'
    - run: npm install -g gulp bower && npm install
      working-directory: ui
    - run: CI=true npm test
      working-directory: ui
    - run: NODE_ENV=production npm run build
      working-directory: ui
