name: Test Cobudget API

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'ui/**'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          cp docker/docker-compose.test.yml docker-compose.override.yml
          docker-compose run cobudget-api
